//
//  MockModel.swift
//  uikit-nba-app
//
//  Created by Ikhsan on 21/08/2022.
//

import Foundation

class MockModel {
    static let teamMockJson =
    """
    [
        {
            "TeamID": 6,
            "Key": "NY",
            "Active": true,
            "City": "New York",
            "Name": "Knicks",
            "LeagueID": 3,
            "StadiumID": 6,
            "Conference": "Eastern",
            "Division": "Atlantic",
            "PrimaryColor": "006BB6",
            "SecondaryColor": "F58426",
            "TertiaryColor": "BEC0C2",
            "QuaternaryColor": "000000",
            "WikipediaLogoUrl": "https://upload.wikimedia.org/wikipedia/en/2/25/New_York_Knicks_logo.svg",
            "WikipediaWordMarkUrl": "",
            "GlobalTeamID": 20000006,
            "NbaDotComTeamID": 1610612752
        },
        {
            "TeamID": 7,
            "Key": "PHI",
            "Active": true,
            "City": "Philadelphia",
            "Name": "76ers",
            "LeagueID": 3,
            "StadiumID": 7,
            "Conference": "Eastern",
            "Division": "Atlantic",
            "PrimaryColor": "006BB6",
            "SecondaryColor": "ED174C",
            "TertiaryColor": "002B5C",
            "QuaternaryColor": "C4CED4",
            "WikipediaLogoUrl": "https://upload.wikimedia.org/wikipedia/en/0/0e/Philadelphia_76ers_logo.svg",
            "WikipediaWordMarkUrl": null,
            "GlobalTeamID": 20000007,
            "NbaDotComTeamID": 1610612755
        },
        {
            "TeamID": 8,
            "Key": "BKN",
            "Active": true,
            "City": "Brooklyn",
            "Name": "Nets",
            "LeagueID": 3,
            "StadiumID": 8,
            "Conference": "Eastern",
            "Division": "Atlantic",
            "PrimaryColor": "000000",
            "SecondaryColor": "FFFFFF",
            "TertiaryColor": "707271",
            "QuaternaryColor": null,
            "WikipediaLogoUrl": "https://upload.wikimedia.org/wikipedia/commons/4/44/Brooklyn_Nets_newlogo.svg",
            "WikipediaWordMarkUrl": null,
            "GlobalTeamID": 20000008,
            "NbaDotComTeamID": 1610612751
        },
        {
            "TeamID": 9,
            "Key": "BOS",
            "Active": true,
            "City": "Boston",
            "Name": "Celtics",
            "LeagueID": 3,
            "StadiumID": 9,
            "Conference": "Eastern",
            "Division": "Atlantic",
            "PrimaryColor": "008348",
            "SecondaryColor": "BB9753",
            "TertiaryColor": "000000",
            "QuaternaryColor": "FFFFFF",
            "WikipediaLogoUrl": "https://upload.wikimedia.org/wikipedia/en/8/8f/Boston_Celtics.svg",
            "WikipediaWordMarkUrl": null,
            "GlobalTeamID": 20000009,
            "NbaDotComTeamID": 1610612738
        },
        {
            "TeamID": 10,
            "Key": "TOR",
            "Active": true,
            "City": "Toronto",
            "Name": "Raptors",
            "LeagueID": 3,
            "StadiumID": 10,
            "Conference": "Eastern",
            "Division": "Atlantic",
            "PrimaryColor": "CE1141",
            "SecondaryColor": "000000",
            "TertiaryColor": "A1A1A4",
            "QuaternaryColor": "B4975A",
            "WikipediaLogoUrl": "https://upload.wikimedia.org/wikipedia/en/3/36/Toronto_Raptors_logo.svg",
            "WikipediaWordMarkUrl": null,
            "GlobalTeamID": 20000010,
            "NbaDotComTeamID": 1610612761
        },
        {
            "TeamID": 11,
            "Key": "CHI",
            "Active": true,
            "City": "Chicago",
            "Name": "Bulls",
            "LeagueID": 3,
            "StadiumID": 11,
            "Conference": "Eastern",
            "Division": "Central",
            "PrimaryColor": "CE1141",
            "SecondaryColor": "000000",
            "TertiaryColor": "",
            "QuaternaryColor": "",
            "WikipediaLogoUrl": "https://upload.wikimedia.org/wikipedia/en/6/67/Chicago_Bulls_logo.svg",
            "WikipediaWordMarkUrl": "",
            "GlobalTeamID": 20000011,
            "NbaDotComTeamID": 1610612741
        }
    ]
    """
    
    
    
    static var mockTeams: [Team] {
        if let data = try? JSONDecoder().decode([Team].self, from: Data(teamMockJson.utf8)) {
            return data
        } else {
            return []
        }
    }
    
    static func mockPlayersByTeam() -> [Player] {
        if let data = try? JSONDecoder().decode([Player].self, from: Data(knicksPlayerMockJson.utf8)) {
            return data
        } else {
            return []
        }
    }
    
    static let knicksPlayerMockJson =
    """
        [
            {
                "PlayerID": 20000516,
                "SportsDataID": "",
                "Status": "Active",
                "TeamID": 6,
                "Team": "NY",
                "Jersey": 4,
                "PositionCategory": "G",
                "Position": "PG",
                "FirstName": "Derrick",
                "LastName": "Rose",
                "Height": 74,
                "Weight": 200,
                "BirthDate": "1988-10-04T00:00:00",
                "BirthCity": "Chicago",
                "BirthState": "IL",
                "BirthCountry": "USA",
                "HighSchool": null,
                "College": "Memphis",
                "Salary": 14520730,
                "PhotoUrl": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nba/low-res/20000516.png",
                "Experience": 12,
                "SportRadarPlayerID": "48341095-ae5a-4d61-bcc8-1b0ceed870b2",
                "RotoworldPlayerID": 1476,
                "RotoWirePlayerID": 2921,
                "FantasyAlarmPlayerID": 200495,
                "StatsPlayerID": 399612,
                "SportsDirectPlayerID": 736477,
                "XmlTeamPlayerID": 1944,
                "InjuryStatus": "Scrambled",
                "InjuryBodyPart": "Scrambled",
                "InjuryStartDate": null,
                "InjuryNotes": "Scrambled",
                "FanDuelPlayerID": 9475,
                "DraftKingsPlayerID": 399612,
                "YahooPlayerID": 4387,
                "FanDuelName": "Derrick Rose",
                "DraftKingsName": "Derrick Rose",
                "YahooName": "Derrick Rose",
                "DepthChartPosition": "PG",
                "DepthChartOrder": 2,
                "GlobalTeamID": 20000006,
                "FantasyDraftName": "Derrick Rose",
                "FantasyDraftPlayerID": 399612,
                "UsaTodayPlayerID": 8248231,
                "UsaTodayHeadshotUpdated": "2022-01-27T10:16:20",
                "UsaTodayHeadshotNoBackgroundUpdated": "2022-01-27T10:16:02",
                "NbaDotComPlayerID": 201565
            },
            {
                "PlayerID": 20000679,
                "SportsDataID": "",
                "Status": "Active",
                "TeamID": 6,
                "Team": "NY",
                "Jersey": 13,
                "PositionCategory": "F",
                "Position": "SF",
                "FirstName": "Evan",
                "LastName": "Fournier",
                "Height": 79,
                "Weight": 205,
                "BirthDate": "1992-10-29T00:00:00",
                "BirthCity": "Saint-Maurice",
                "BirthState": null,
                "BirthCountry": "France",
                "HighSchool": null,
                "College": "None",
                "Salary": 18000000,
                "PhotoUrl": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nba/low-res/20000679.png",
                "Experience": 9,
                "SportRadarPlayerID": "b736d95c-8474-48b2-9000-24ce926eace3",
                "RotoworldPlayerID": 1983,
                "RotoWirePlayerID": 3317,
                "FantasyAlarmPlayerID": 200440,
                "StatsPlayerID": 659767,
                "SportsDirectPlayerID": 751207,
                "XmlTeamPlayerID": 3414,
                "InjuryStatus": "Scrambled",
                "InjuryBodyPart": "Scrambled",
                "InjuryStartDate": null,
                "InjuryNotes": "Scrambled",
                "FanDuelPlayerID": 23096,
                "DraftKingsPlayerID": 659767,
                "YahooPlayerID": 5054,
                "FanDuelName": "Evan Fournier",
                "DraftKingsName": "Evan Fournier",
                "YahooName": "Evan Fournier",
                "DepthChartPosition": "SG",
                "DepthChartOrder": 1,
                "GlobalTeamID": 20000006,
                "FantasyDraftName": "Evan Fournier",
                "FantasyDraftPlayerID": 659767,
                "UsaTodayPlayerID": 8277218,
                "UsaTodayHeadshotUpdated": "2021-10-11T21:40:53",
                "UsaTodayHeadshotNoBackgroundUpdated": "2021-10-11T21:40:44",
                "NbaDotComPlayerID": 203095
            },
            {
                "PlayerID": 20000710,
                "SportsDataID": "",
                "Status": "Active",
                "TeamID": 6,
                "Team": "NY",
                "Jersey": 30,
                "PositionCategory": "F",
                "Position": "PF",
                "FirstName": "Julius",
                "LastName": "Randle",
                "Height": 80,
                "Weight": 250,
                "BirthDate": "1994-11-29T00:00:00",
                "BirthCity": "Dallas",
                "BirthState": "TX",
                "BirthCountry": "USA",
                "HighSchool": null,
                "College": "Kentucky",
                "Salary": 23760000,
                "PhotoUrl": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nba/low-res/20000710.png",
                "Experience": 7,
                "SportRadarPlayerID": "24c85a15-686e-4161-934b-40948188fa36",
                "RotoworldPlayerID": 2352,
                "RotoWirePlayerID": 3574,
                "FantasyAlarmPlayerID": 200253,
                "StatsPlayerID": 786412,
                "SportsDirectPlayerID": 756761,
                "XmlTeamPlayerID": 3728,
                "InjuryStatus": "Scrambled",
                "InjuryBodyPart": "Scrambled",
                "InjuryStartDate": null,
                "InjuryNotes": "Scrambled",
                "FanDuelPlayerID": 42669,
                "DraftKingsPlayerID": 786412,
                "YahooPlayerID": 5318,
                "FanDuelName": "Julius Randle",
                "DraftKingsName": "Julius Randle",
                "YahooName": "Julius Randle",
                "DepthChartPosition": "PF",
                "DepthChartOrder": 1,
                "GlobalTeamID": 20000006,
                "FantasyDraftName": "Julius Randle",
                "FantasyDraftPlayerID": 786412,
                "UsaTodayPlayerID": 8248224,
                "UsaTodayHeadshotUpdated": "2021-11-21T20:25:51",
                "UsaTodayHeadshotNoBackgroundUpdated": "2021-11-30T11:40:47",
                "NbaDotComPlayerID": 203944
            },
            {
                "PlayerID": 20002016,
                "SportsDataID": "",
                "Status": "Active",
                "TeamID": 6,
                "Team": "NY",
                "Jersey": 23,
                "PositionCategory": "C",
                "Position": "C",
                "FirstName": "Mitchell",
                "LastName": "Robinson",
                "Height": 84,
                "Weight": 240,
                "BirthDate": "1998-04-01T00:00:00",
                "BirthCity": "Pensacola",
                "BirthState": "FL",
                "BirthCountry": "USA",
                "HighSchool": null,
                "College": "Western Kentucky",
                "Salary": 17045454,
                "PhotoUrl": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nba/low-res/20002016.png",
                "Experience": 3,
                "SportRadarPlayerID": "97e25d19-7c5c-49f9-91c0-5cd9b9cebdcb",
                "RotoworldPlayerID": 2946,
                "RotoWirePlayerID": 4426,
                "FantasyAlarmPlayerID": 201125,
                "StatsPlayerID": 1076265,
                "SportsDirectPlayerID": 779964,
                "XmlTeamPlayerID": null,
                "InjuryStatus": "Scrambled",
                "InjuryBodyPart": "Scrambled",
                "InjuryStartDate": null,
                "InjuryNotes": "Scrambled",
                "FanDuelPlayerID": 84709,
                "DraftKingsPlayerID": 1076265,
                "YahooPlayerID": 6047,
                "FanDuelName": "Mitchell Robinson",
                "DraftKingsName": "Mitchell Robinson",
                "YahooName": "Mitchell Robinson",
                "DepthChartPosition": "C",
                "DepthChartOrder": 1,
                "GlobalTeamID": 20000006,
                "FantasyDraftName": "Mitchell Robinson",
                "FantasyDraftPlayerID": 1076265,
                "UsaTodayPlayerID": 8248229,
                "UsaTodayHeadshotUpdated": "2019-10-09T17:16:12",
                "UsaTodayHeadshotNoBackgroundUpdated": "2019-10-14T10:00:35",
                "NbaDotComPlayerID": 1629011
            },
            {
                "PlayerID": 20002032,
                "SportsDataID": "",
                "Status": "Active",
                "TeamID": 6,
                "Team": "NY",
                "Jersey": 11,
                "PositionCategory": "G",
                "Position": "PG",
                "FirstName": "Jalen",
                "LastName": "Brunson",
                "Height": 73,
                "Weight": 190,
                "BirthDate": "1996-08-31T00:00:00",
                "BirthCity": "New Brunswick",
                "BirthState": "NJ",
                "BirthCountry": "USA",
                "HighSchool": null,
                "College": "Villanova",
                "Salary": 27733332,
                "PhotoUrl": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nba/low-res/20002032.png",
                "Experience": 2,
                "SportRadarPlayerID": "8d3edba8-9004-4199-9328-cc2208e8b0d3",
                "RotoworldPlayerID": 2983,
                "RotoWirePlayerID": 4405,
                "FantasyAlarmPlayerID": 201137,
                "StatsPlayerID": 887914,
                "SportsDirectPlayerID": 767283,
                "XmlTeamPlayerID": null,
                "InjuryStatus": "Scrambled",
                "InjuryBodyPart": "Scrambled",
                "InjuryStartDate": null,
                "InjuryNotes": "Scrambled",
                "FanDuelPlayerID": 84690,
                "DraftKingsPlayerID": 887914,
                "YahooPlayerID": 6044,
                "FanDuelName": "Jalen Brunson",
                "DraftKingsName": "Jalen Brunson",
                "YahooName": "Jalen Brunson",
                "DepthChartPosition": "PG",
                "DepthChartOrder": 1,
                "GlobalTeamID": 20000006,
                "FantasyDraftName": "Jalen Brunson",
                "FantasyDraftPlayerID": 887914,
                "UsaTodayPlayerID": 8256658,
                "UsaTodayHeadshotUpdated": "2021-10-07T11:15:27",
                "UsaTodayHeadshotNoBackgroundUpdated": "2021-10-08T22:25:04",
                "NbaDotComPlayerID": 1628973
            },
            {
                "PlayerID": 20002272,
                "SportsDataID": "",
                "Status": "Active",
                "TeamID": 6,
                "Team": "NY",
                "Jersey": 9,
                "PositionCategory": "G",
                "Position": "SG",
                "FirstName": "RJ",
                "LastName": "Barrett",
                "Height": 78,
                "Weight": 214,
                "BirthDate": "2000-06-14T00:00:00",
                "BirthCity": "Toronto",
                "BirthState": "ON",
                "BirthCountry": "Canada",
                "HighSchool": null,
                "College": "Duke",
                "Salary": 10900635,
                "PhotoUrl": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nba/low-res/20002272.png",
                "Experience": 2,
                "SportRadarPlayerID": "42c5f009-dfd2-4a94-a750-0943791e138e",
                "RotoworldPlayerID": 3101,
                "RotoWirePlayerID": 4767,
                "FantasyAlarmPlayerID": 201256,
                "StatsPlayerID": 1132031,
                "SportsDirectPlayerID": 785220,
                "XmlTeamPlayerID": null,
                "InjuryStatus": "Scrambled",
                "InjuryBodyPart": "Scrambled",
                "InjuryStartDate": null,
                "InjuryNotes": "Scrambled",
                "FanDuelPlayerID": 110357,
                "DraftKingsPlayerID": 1132031,
                "YahooPlayerID": 6165,
                "FanDuelName": "RJ Barrett",
                "DraftKingsName": "RJ Barrett",
                "YahooName": "RJ Barrett",
                "DepthChartPosition": "SF",
                "DepthChartOrder": 1,
                "GlobalTeamID": 20000006,
                "FantasyDraftName": "RJ Barrett",
                "FantasyDraftPlayerID": 1132031,
                "UsaTodayPlayerID": 8248168,
                "UsaTodayHeadshotUpdated": "2021-12-09T18:54:32",
                "UsaTodayHeadshotNoBackgroundUpdated": "2021-12-14T13:33:18",
                "NbaDotComPlayerID": 1629628
            }
        ]
    """
    
}
